---
    - id: copyright-year-check
      description: Checks weather a files copyright header includes the current year.
      entry: check_copyright.sh
      language: script
      name: Copyright year check
      types: [text]
